name: Compile & Package

on:
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Environment setup
      run: |
        echo 'ROOT_DIR=$PWD'>> $GITHUB_ENV
        echo 'BUILD_DIR=$PWD/build'>> $GITHUB_ENV

    - name: pre-requisite installation
      run: |
        sudo apt-get update
        sudo apt-get install tree autotools-dev autoconf automake libtool pkg-config cmake texinfo texlive

    - name: Folders listing
      run: |
        echo $PWD
        ls -ls
        cd ..
        echo $PWD
        echo 'ROOT_DIR=$ROOT_DIR'
        echo 'BUILD_DIR=$BUILD_DIR'
        ls -ls
        tree -a
        env
        cat $GITHUB_ENV
        gcc --version

    - name: Building
      run: |
        cd $GITHUB_WORKSPACE
        gcc -o $BUILD_DIR/test entry.c

      
