name: Compile & Package

on:
  workflow_dispatch:

# default working directory for every jobs set to checkout dir
# /home/runner/work/<git dir>/<checkout git dir> <== default working directory

jobs:
  build-package:
    runs-on: ubuntu-20.04
    env:
      LIBUSB1_VER: 1.0.26
      HIDAPI_VER: 0.11.2
      LIBFTDI_VER: 1.5
      CAPSTONE_VER: 5.0-rc2
      PREFIX: '/usr'

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Environment setup
      run: |
        cat $GITHUB_ENV
        cd ..
        echo "ROOT_DIR=$PWD" >> $GITHUB_ENV
        echo "BUILD_DIR=$PWD/build" >> $GITHUB_ENV
        echo "DOWNLOAD_DIR=$PWD/download" >> $GITHUB_ENV
        echo "SYSROOT=$PWD/root" >> $GITHUB_ENV

        echo "LIBUSB1_SRC=$PWD/download/libusb-${LIBUSB1_VER}" >> $GITHUB_ENV
        echo "HIDAPI_SRC=$PWD/download/hidapi-hidapi-${HIDAPI_VER}" >> $GITHUB_ENV
        echo "LIBFTDI_SRC=$PWD/download/libftdi1-${LIBFTDI_VER}" >> $GITHUB_ENV
        echo "CAPSTONE_SRC=$PWD/download/capstone-${CAPSTONE_VER}" >> $GITHUB_ENV

        echo "BUILD_USB1_DIR=$PWD/build/libusb1" >> $GITHUB_ENV
        echo "BUILD_HIDAPI_DIR=$PWD/build/hidapi" >> $GITHUB_ENV
        echo "BUILD_FTDI_DIR=$PWD/build/libftdi" >> $GITHUB_ENV
        echo "BUILD_CAPSTONE_DIR=$PWD/build/capstone" >> $GITHUB_ENV
        echo "BUILD_OPENOCD_DIR=$PWD/build/openocd" >> $GITHUB_ENV

    - name: pre-requisite installation
      run: |
        mkdir -p $SYSROOT $BUILD_DIR $DOWNLOAD_DIR $BUILD_USB1_DIR $BUILD_HIDAPI_DIR $BUILD_FTDI_DIR $BUILD_CAPSTONE_DIR $BUILD_OPENOCD_DIR
        sudo apt-get update
        sudo apt-get install tree autotools-dev autoconf automake libtool pkg-config cmake texinfo texlive

    - name: Download dependencies
      run: |
        cd $DOWNLOAD_DIR
        apt download libudev1 libudev-dev
        find . -iname '*.deb' -exec dpkg -x '{}' $SYSROOT \;
        sudo dpkg -i *.deb

        cd $ROOT_DIR
        tree -a
        cd $DOWNLOAD_DIR

        wget "https://github.com/libusb/libusb/releases/download/v${LIBUSB1_VER}/libusb-${LIBUSB1_VER}.tar.bz2"
        tar -xjf libusb-${LIBUSB1_VER}.tar.bz2

        wget "http://www.intra2net.com/en/developer/libftdi/download/libftdi1-${LIBFTDI_VER}.tar.bz2"
        tar -xjf libftdi1-${LIBFTDI_VER}.tar.bz2

        wget "https://github.com/aquynh/capstone/archive/${CAPSTONE_VER}.tar.gz"
        # tar -xzf ${CAPSTONE_VER}.tar.gz

        wget "https://github.com/libusb/hidapi/archive/hidapi-${HIDAPI_VER}.tar.gz"
        tar -xzf hidapi-${HIDAPI_VER}.tar.gz

    - name: Building
      env:
        PKG_CONFIG_DIR: ""
        # PKG_CONFIG_PATH: ""
      run: |
        export PKG_CONFIG_LIBDIR="$SYSROOT$PREFIX/lib/pkgconfig:$SYSROOT$PREFIX/share/pkgconfig:$SYSROOT$PREFIX/lib/x86_64-linux-gnu/pkgconfig"
        export PKG_CONFIG_SYSROOT_DIR=$SYSROOT
        # export PKG_CONFIG_PATH="$SYSROOT$PREFIX/lib/pkgconfig:$SYSROOT$PREFIX/share/pkgconfig"
        echo $PKG_CONFIG_SYSROOT_DIR
        echo $PKG_CONFIG_LIBDIR

        cd $BUILD_USB1_DIR
        $LIBUSB1_SRC/configure --build=`$LIBUSB1_SRC/config.guess` --with-sysroot=$SYSROOT --prefix=$PREFIX
        make -j
        make install DESTDIR=$SYSROOT

        cd $SYSROOT
        tree -a

        cat ./usr/lib/pkgconfig/libusb-1.0.pc
        pkg-config --variable pc_path pkg-config
        pkg-config --exists --print-errors libusb-1.0
        pkg-config --variable=includedir libusb-1.0
        pkg-config --variable=libdir libusb-1.0
        pkg-config --variable=pcfiledir libusb-1.0

        cd $HIDAPI_SRC
        ./bootstrap
        cd $BUILD_HIDAPI_DIR
        $HIDAPI_SRC/configure --build=`$HIDAPI_SRC/config.guess` --with-sysroot=$SYSROOT --prefix=$PREFIX
        cat config.log
        make -n
        make install DESTDIR=$SYSROOT

        cd $SYSROOT
        tree -a

        cd $BUILD_CAPSTONE_DIR
        tar -xzf $DOWNLOAD_DIR/${CAPSTONE_VER}.tar.gz
        make install DESTDIR=$SYSROOT PREFIX=$PREFIX

        cd $SYSROOT
        tree -a

        cd $GITHUB_WORKSPACE
        gcc -o $BUILD_DIR/test entry.c

